# Generated by Django 4.2.16 on 2024-11-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='desc',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
