# Generated by Django 4.2.16 on 2024-12-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0004_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='grams_per_unit',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10, verbose_name='Граммы на единицу измерения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'граммы'), ('ml', 'миллилитры'), ('pcs', 'штуки'), ('tsp', 'чайные ложки'), ('tbsp', 'столовые ложки')], default='g', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='raw_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Сырой вес'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес после обработки'),
        ),
    ]
