# Generated by Django 4.2.16 on 2024-12-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0006_alter_ingredient_calorific_alter_ingredient_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calorific',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Калорийность, ккал'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость, руб'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='grams_per_unit',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Грамм на единицу измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='raw_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Сырой вес, г'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес после обработки, г'),
        ),
    ]
