# Generated by Django 4.2.16 on 2024-12-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0007_alter_ingredient_calorific_alter_ingredient_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='additional_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Дополнительное количество'),
        ),
    ]
