# Generated by Django 4.2.16 on 2024-12-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0008_ingredient_additional_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='additional_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
