# Generated by Django 4.2.16 on 2024-12-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0009_alter_ingredient_additional_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calorific',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Калорийность (на 100 г), ккал'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
