# Generated by Django 4.2.16 on 2024-12-28 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0010_alter_ingredient_calorific_alter_recipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.TimeField(default=datetime.time(0, 30), verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='desc',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
